import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div  >
        <header className=" ">
          <nav className="flex justify-between ">
            <div className="">
              {/* <img src="https://st2.depositphotos.com/4035913/6124/i/380/depositphotos_61243733-stock-illustration-business-company-logo.jpg" alt="" /> */}
            </div>
            <ul className="flex gap-6 ">
              <li>home</li>
              <li className="">about</li>
              <li>contact</li>
            </ul>
          </nav>
        </header>
      </div>
        {children}
        </body>
    </html>
  );
}
